<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Title>Sheas Cealer Droid</Title>
		<Product>Sheas Cealer Droid</Product>
		<Trademark>Sheas Cealer Droid</Trademark>
		<ApplicationTitle>Cealer</ApplicationTitle>
		<ApplicationId>spacetime.sheas.cealer</ApplicationId>
		<Description>Ceal It</Description>
		<PackageReleaseNotes>Ceal It</PackageReleaseNotes>
		<Authors>Space Time</Authors>
		<Company>SpaceTime Studio</Company>
		<AssemblyVersion>1.0.2</AssemblyVersion>
		<Version>1.0.2</Version>
		<FileVersion>1.0.2</FileVersion>
		<InformationalVersion>1.0.2</InformationalVersion>
		<ApplicationDisplayVersion>1.0.2</ApplicationDisplayVersion>
		<ApplicationVersion>3</ApplicationVersion>
		<PackageTags>Tool;Sheas;Cealer;Droid;Sni</PackageTags>
		<PackageIcon>Sheas Cealer Droid Logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageProjectUrl>https://github.com/SpaceTimee/Sheas-Cealer-Droid</PackageProjectUrl>
		<RepositoryUrl>https://github.com/SpaceTimee/Sheas-Cealer-Droid</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<Copyright>Copyright © 2077</Copyright>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net9.0-android</TargetFrameworks>
		<SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
		<RootNamespace>Sheas_Cealer_Droid</RootNamespace>
		<Nullable>enable</Nullable>
		<UseMaui>true</UseMaui>
		<MauiVersion>9.0.80</MauiVersion>
		<MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>disable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
		<ErrorReport>none</ErrorReport>
		<PlatformsProjectFolder>Plats</PlatformsProjectFolder>
		<AppDesignerFolder>Props</AppDesignerFolder>
		<NeutralLanguage>en</NeutralLanguage>
		<EnableLLVM>true</EnableLLVM>
		<RunAOTCompilation>false</RunAOTCompilation>
		<AndroidEnableMarshalMethods>false</AndroidEnableMarshalMethods>
		<AndroidKeyStore>false</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<AndroidLinkTool>r8</AndroidLinkTool>
	</PropertyGroup>

	<ItemGroup>
		<MauiIcon Include="Rsces\Logos\app_bkgd.svg" ForegroundFile="Rsces\Logos\app_logo.png" Color="#FFE9EE" ForegroundScale="0.5" />
		<MauiSplashScreen Include="Rsces\Logos\app_logo.png" Color="#FFE9EE" />
		<MauiImage Include="Rsces\Images\*" />
		<MauiImage Include="Rsces\Logos\app_logo.png" BaseSize="256,256" />
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="Pages\AboutPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\BrowserPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\AdbPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\ReadyPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\FlagPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\ToolPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\SettingsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Rsces\Colors\PinkBlueColor.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Rsces\Colors\GreenColor.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Rsces\Colors\YellowColor.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Rsces\Colors\OrangeColor.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Rsces\Colors\BlueColor.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Rsces\Colors\RedColor.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Rsces\Tmpls\BaseTmpl.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

	<ItemGroup>
		<None Remove=".filenesting.json" />
		<None Remove=".gitattributes" />
		<None Remove=".gitignore" />
		<None Remove="README.md" />
		<None Remove="README_EN.md" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="12.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Ona-Core">
			<HintPath>Ona-Core.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Consts\AboutMultilangConst.Designer.cs">
			<DependentUpon>AboutMultilangConst.resx</DependentUpon>
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
		</Compile>
		<Compile Update="Consts\AdbMultilangConst.Designer.cs">
			<DependentUpon>AdbMultilangConst.resx</DependentUpon>
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
		</Compile>
		<Compile Update="Consts\ToolMultilangConst.Designer.cs">
			<DependentUpon>ToolMultilangConst.resx</DependentUpon>
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
		</Compile>
		<Compile Update="Consts\SettingsMultilangConst.Designer.cs">
			<DependentUpon>SettingsMultilangConst.resx</DependentUpon>
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
		</Compile>
		<Compile Update="Consts\BrowserMultilangConst.Designer.cs">
			<DependentUpon>BrowserMultilangConst.resx</DependentUpon>
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
		</Compile>
		<Compile Update="Consts\FlagMultilangConst.Designer.cs">
			<DependentUpon>FlagMultilangConst.resx</DependentUpon>
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
		</Compile>
		<Compile Update="Consts\AppMultilangConst.Designer.cs">
			<DependentUpon>AppMultilangConst.resx</DependentUpon>
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
		</Compile>
		<Compile Update="Consts\ReadyMultilangConst.Designer.cs">
			<DependentUpon>ReadyMultilangConst.resx</DependentUpon>
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
		</Compile>
		<Compile Update="Consts\MainMultilangConst.Designer.cs">
			<DependentUpon>MainMultilangConst.resx</DependentUpon>
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
		</Compile>
		<Compile Update="Consts\GlobalMultilangConst.Designer.cs">
			<DependentUpon>GlobalMultilangConst.resx</DependentUpon>
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Consts\AboutMultilangConst.resx">
			<LastGenOutput>AboutMultilangConst.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Consts\AdbMultilangConst.resx">
			<LastGenOutput>AdbMultilangConst.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Consts\ToolMultilangConst.resx">
			<LastGenOutput>ToolMultilangConst.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Consts\SettingsMultilangConst.resx">
			<LastGenOutput>SettingsMultilangConst.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Consts\BrowserMultilangConst.resx">
			<LastGenOutput>BrowserMultilangConst.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Consts\FlagMultilangConst.resx">
			<LastGenOutput>FlagMultilangConst.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Consts\AppMultilangConst.resx">
			<LastGenOutput>AppMultilangConst.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Consts\ReadyMultilangConst.resx">
			<LastGenOutput>ReadyMultilangConst.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Consts\MainMultilangConst.resx">
			<LastGenOutput>MainMultilangConst.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Consts\GlobalMultilangConst.resx">
			<LastGenOutput>GlobalMultilangConst.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
	</ItemGroup>

</Project>
